name: 'Terraform destroy'

on:
  workflow_dispatch:
    inputs:
      perform_apply_destroy:
        type: boolean
        description: Destroy Resources
      

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform destroy'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan Destroy
      run: terraform plan -destroy

      if: ${{ inputs.perform_apply_destroy }}
    - name: Terraform Apply Destroy
      run: terraform apply -destroy